CREATE TABLE designs (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	image VARCHAR(100) NOT NULL,
	reg_date TIMESTAMP
);

CREATE TABLE products (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    design_id int,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(100) NOT NULL,
    FOREIGN KEY (design_id) REFERENCES designs(id)
);

CREATE TABLE product_images (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id int(10) UNSIGNED NOT NULL,
    image VARCHAR(100) NOT NULL
);

CREATE TABLE fillings (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	image VARCHAR(100) NULL,
	reg_date TIMESTAMP
);

CREATE TABLE flavour_filling (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	flavour_id INT(10) UNSIGNED NOT NULL,
	filling_id INT(10) UNSIGNED NOT NULL,
	reg_date TIMESTAMP
);

CREATE TABLE tiers (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	image VARCHAR(100) NOT NULL,
	reg_date TIMESTAMP
);

CREATE TABLE shapes (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	image VARCHAR(100) NOT NULL,
	reg_date TIMESTAMP
);

CREATE TABLE sizes (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	image VARCHAR(100) NULL,
	created_at TIMESTAMP
);

CREATE TABLE servings (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	tier_id INT(10) UNSIGNED NOT NULL,
	shape_id INT(10) UNSIGNED NOT NULL,
    size_id INT(10) UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
	created_at TIMESTAMP
);

INSERT INTO `designs` (`id`, `parent_id`, `name`, `image`, `created_at`) VALUES 
('2', NULL, 'Adults Birthday Cakes', 'adult-bd-cakes.jpg', CURRENT_TIMESTAMP),
('3', NULL, 'Cupcakes/ Mini Cakes', 'cupcakes-mini-cakes.jpg', CURRENT_TIMESTAMP),
('4', NULL, 'Wedding Cakes', 'wedding-cakes.jpg', CURRENT_TIMESTAMP),
('5', NULL, 'Christening Cakes', 'christening-cakes.jpg', CURRENT_TIMESTAMP),
('6', NULL, 'Naming & Baby Shower Cakes', 'naming-baby-shower-cakes.jpg', CURRENT_TIMESTAMP);

INSERT INTO `flavours` (`id`, `parent_id`, `name`, `image`, `created_at`) VALUES (NULL, NULL, 'Sponge Cake', 'sponge-cake.jpg', CURRENT_TIMESTAMP);

INSERT INTO `fillings` (`id`, `name`, `image`, `created_at`) VALUES (NULL, 'Lime Flavoured', NULL, CURRENT_TIMESTAMP)

INSERT INTO `flavour_filling` (`id`, `flavour_id`, `filling_id`, `created_at`) VALUES 
(NULL, '11', '1', CURRENT_TIMESTAMP),
(NULL, '11', '2', CURRENT_TIMESTAMP),
(NULL, '11', '3', CURRENT_TIMESTAMP),
(NULL, '11', '4', CURRENT_TIMESTAMP),
(NULL, '11', '5', CURRENT_TIMESTAMP),
(NULL, '11', '6', CURRENT_TIMESTAMP),
(NULL, '11', '7', CURRENT_TIMESTAMP),
(NULL, '11', '8', CURRENT_TIMESTAMP),
(NULL, '11', '9', CURRENT_TIMESTAMP),
(NULL, '11', '10', CURRENT_TIMESTAMP),
(NULL, '11', '11', CURRENT_TIMESTAMP),
(NULL, '11', '12', CURRENT_TIMESTAMP),
(NULL, '11', '13', CURRENT_TIMESTAMP),
(NULL, '11', '14', CURRENT_TIMESTAMP),
(NULL, '11', '15', CURRENT_TIMESTAMP),
(NULL, '3', '1', CURRENT_TIMESTAMP),
(NULL, '3', '3', CURRENT_TIMESTAMP),
(NULL, '3', '4', CURRENT_TIMESTAMP),
(NULL, '3', '9', CURRENT_TIMESTAMP),
(NULL, '3', '10', CURRENT_TIMESTAMP),
(NULL, '3', '11', CURRENT_TIMESTAMP),
(NULL, '4', '2', CURRENT_TIMESTAMP),

(NULL, '12', '1', CURRENT_TIMESTAMP),
(NULL, '12', '3', CURRENT_TIMESTAMP),
(NULL, '12', '4', CURRENT_TIMESTAMP),
(NULL, '12', '9', CURRENT_TIMESTAMP),
(NULL, '12', '10', CURRENT_TIMESTAMP),
(NULL, '12', '11', CURRENT_TIMESTAMP),

(NULL, '13', '1', CURRENT_TIMESTAMP),
(NULL, '13', '3', CURRENT_TIMESTAMP),
(NULL, '13', '6', CURRENT_TIMESTAMP),
(NULL, '13', '7', CURRENT_TIMESTAMP),
(NULL, '13', '8', CURRENT_TIMESTAMP),

(NULL, '14', '1', CURRENT_TIMESTAMP),
(NULL, '14', '2', CURRENT_TIMESTAMP),
(NULL, '14', '3', CURRENT_TIMESTAMP),
(NULL, '14', '4', CURRENT_TIMESTAMP),
(NULL, '14', '5', CURRENT_TIMESTAMP),
(NULL, '14', '6', CURRENT_TIMESTAMP),
(NULL, '14', '7', CURRENT_TIMESTAMP),
(NULL, '14', '8', CURRENT_TIMESTAMP),
(NULL, '14', '9', CURRENT_TIMESTAMP),
(NULL, '14', '10', CURRENT_TIMESTAMP),
(NULL, '14', '11', CURRENT_TIMESTAMP),
(NULL, '14', '12', CURRENT_TIMESTAMP),
(NULL, '14', '13', CURRENT_TIMESTAMP),
(NULL, '14', '14', CURRENT_TIMESTAMP),
(NULL, '14', '15', CURRENT_TIMESTAMP),

(NULL, '15', '1', CURRENT_TIMESTAMP),
(NULL, '15', '3', CURRENT_TIMESTAMP),
(NULL, '15', '4', CURRENT_TIMESTAMP),
(NULL, '15', '9', CURRENT_TIMESTAMP),
(NULL, '15', '10', CURRENT_TIMESTAMP),
(NULL, '15', '11', CURRENT_TIMESTAMP),

(NULL, '16', '1', CURRENT_TIMESTAMP),
(NULL, '16', '2', CURRENT_TIMESTAMP),
(NULL, '16', '3', CURRENT_TIMESTAMP),
(NULL, '16', '4', CURRENT_TIMESTAMP),
(NULL, '16', '5', CURRENT_TIMESTAMP),
(NULL, '16', '6', CURRENT_TIMESTAMP),
(NULL, '16', '7', CURRENT_TIMESTAMP),
(NULL, '16', '8', CURRENT_TIMESTAMP),
(NULL, '16', '9', CURRENT_TIMESTAMP),
(NULL, '16', '10', CURRENT_TIMESTAMP),
(NULL, '16', '11', CURRENT_TIMESTAMP),
(NULL, '16', '12', CURRENT_TIMESTAMP),
(NULL, '16', '13', CURRENT_TIMESTAMP),
(NULL, '16', '14', CURRENT_TIMESTAMP),
(NULL, '16', '15', CURRENT_TIMESTAMP),

(NULL, '17', '1', CURRENT_TIMESTAMP),
(NULL, '17', '3', CURRENT_TIMESTAMP),
(NULL, '17', '4', CURRENT_TIMESTAMP),
(NULL, '17', '9', CURRENT_TIMESTAMP),
(NULL, '17', '10', CURRENT_TIMESTAMP),
(NULL, '17', '11', CURRENT_TIMESTAMP),

(NULL, '18', '1', CURRENT_TIMESTAMP),
(NULL, '18', '2', CURRENT_TIMESTAMP),
(NULL, '18', '3', CURRENT_TIMESTAMP),
(NULL, '18', '4', CURRENT_TIMESTAMP),
(NULL, '18', '5', CURRENT_TIMESTAMP),
(NULL, '18', '6', CURRENT_TIMESTAMP),
(NULL, '18', '7', CURRENT_TIMESTAMP),
(NULL, '18', '8', CURRENT_TIMESTAMP),
(NULL, '18', '9', CURRENT_TIMESTAMP),
(NULL, '18', '10', CURRENT_TIMESTAMP),
(NULL, '18', '11', CURRENT_TIMESTAMP),
(NULL, '18', '12', CURRENT_TIMESTAMP),
(NULL, '18', '13', CURRENT_TIMESTAMP),
(NULL, '18', '14', CURRENT_TIMESTAMP),
(NULL, '18', '15', CURRENT_TIMESTAMP),

(NULL, '19', '1', CURRENT_TIMESTAMP),
(NULL, '19', '3', CURRENT_TIMESTAMP),
(NULL, '19', '4', CURRENT_TIMESTAMP),
(NULL, '19', '9', CURRENT_TIMESTAMP),
(NULL, '19', '10', CURRENT_TIMESTAMP),
(NULL, '19', '11', CURRENT_TIMESTAMP),

(NULL, '20', '1', CURRENT_TIMESTAMP),
(NULL, '20', '2', CURRENT_TIMESTAMP),
(NULL, '20', '3', CURRENT_TIMESTAMP),
(NULL, '20', '4', CURRENT_TIMESTAMP),
(NULL, '20', '5', CURRENT_TIMESTAMP),
(NULL, '20', '6', CURRENT_TIMESTAMP),
(NULL, '20', '7', CURRENT_TIMESTAMP),
(NULL, '20', '8', CURRENT_TIMESTAMP),
(NULL, '20', '9', CURRENT_TIMESTAMP),
(NULL, '20', '10', CURRENT_TIMESTAMP),
(NULL, '20', '11', CURRENT_TIMESTAMP),
(NULL, '20', '12', CURRENT_TIMESTAMP),
(NULL, '20', '13', CURRENT_TIMESTAMP),
(NULL, '20', '14', CURRENT_TIMESTAMP),
(NULL, '20', '15', CURRENT_TIMESTAMP),

(NULL, '21', '1', CURRENT_TIMESTAMP),
(NULL, '21', '3', CURRENT_TIMESTAMP),
(NULL, '21', '4', CURRENT_TIMESTAMP),
(NULL, '21', '9', CURRENT_TIMESTAMP),
(NULL, '21', '10', CURRENT_TIMESTAMP),
(NULL, '21', '11', CURRENT_TIMESTAMP);

INSERT INTO `sizes` (`id`, `name`, `created_at`) VALUES (NULL, '6', CURRENT_TIMESTAMP),
(NULL, '6,10', CURRENT_TIMESTAMP),
(NULL, '8,12', CURRENT_TIMESTAMP),
(NULL, '6,8,10', CURRENT_TIMESTAMP),
(NULL, '6,9,12', CURRENT_TIMESTAMP),
(NULL, '8,10,12', CURRENT_TIMESTAMP),
(NULL, '6,8,10,12', CURRENT_TIMESTAMP),
(NULL, '8,10,12,14', CURRENT_TIMESTAMP),
(NULL, '6,8,10,12,14', CURRENT_TIMESTAMP);

INSERT INTO `servings` (`id`, `tier_id`, `shape_id`, `size_id`, `name`, `created_at`) VALUES 
(NULL, '1', '1', '1', '8', CURRENT_TIMESTAMP),
(NULL, '1', '1', '2', '11', CURRENT_TIMESTAMP),
(NULL, '1', '1', '3', '15', CURRENT_TIMESTAMP),
(NULL, '1', '1', '4', '20', CURRENT_TIMESTAMP),
(NULL, '1', '1', '5', '27', CURRENT_TIMESTAMP),
(NULL, '1', '1', '6', '38', CURRENT_TIMESTAMP),
(NULL, '1', '1', '7', '45', CURRENT_TIMESTAMP),
(NULL, '1', '1', '8', '56', CURRENT_TIMESTAMP),
(NULL, '1', '1', '9', '64', CURRENT_TIMESTAMP),

(NULL, '1', '2', '1', '8', CURRENT_TIMESTAMP),
(NULL, '1', '2', '2', '18', CURRENT_TIMESTAMP),
(NULL, '1', '2', '3', '24', CURRENT_TIMESTAMP),
(NULL, '1', '2', '4', '32', CURRENT_TIMESTAMP),
(NULL, '1', '2', '5', '35', CURRENT_TIMESTAMP),
(NULL, '1', '2', '6', '50', CURRENT_TIMESTAMP),
(NULL, '1', '2', '7', '56', CURRENT_TIMESTAMP),
(NULL, '1', '2', '8', '72', CURRENT_TIMESTAMP),
(NULL, '1', '2', '9', '98', CURRENT_TIMESTAMP),

(NULL, '1', '3', '1', '6', CURRENT_TIMESTAMP),
(NULL, '1', '3', '2', '12', CURRENT_TIMESTAMP),
(NULL, '1', '3', '3', '16', CURRENT_TIMESTAMP),
(NULL, '1', '3', '4', '24', CURRENT_TIMESTAMP),
(NULL, '1', '3', '5', '28', CURRENT_TIMESTAMP),
(NULL, '1', '3', '6', '30', CURRENT_TIMESTAMP),
(NULL, '1', '3', '7', '35', CURRENT_TIMESTAMP),
(NULL, '1', '3', '8', '40', CURRENT_TIMESTAMP),
(NULL, '1', '3', '9', '45', CURRENT_TIMESTAMP),

(NULL, '2', '1', '10', '49', CURRENT_TIMESTAMP),
(NULL, '2', '1', '11', '76', CURRENT_TIMESTAMP),
(NULL, '2', '1', '12', '69', CURRENT_TIMESTAMP),
(NULL, '2', '1', '13', '94', CURRENT_TIMESTAMP),
(NULL, '2', '1', '14', '114', CURRENT_TIMESTAMP),
(NULL, '2', '1', '15', '125', CURRENT_TIMESTAMP),
(NULL, '2', '1', '16', '169', CURRENT_TIMESTAMP),
(NULL, '2', '1', '17', '189', CURRENT_TIMESTAMP),

(NULL, '2', '2', '10', '68', CURRENT_TIMESTAMP),
(NULL, '2', '2', '11', '104', CURRENT_TIMESTAMP),
(NULL, '2', '2', '12', '100', CURRENT_TIMESTAMP),
(NULL, '2', '2', '13', '125', CURRENT_TIMESTAMP),
(NULL, '2', '2', '14', '154', CURRENT_TIMESTAMP),
(NULL, '2', '2', '15', '172', CURRENT_TIMESTAMP),
(NULL, '2', '2', '16', '308', CURRENT_TIMESTAMP),
(NULL, '2', '2', '17', '326', CURRENT_TIMESTAMP),

(NULL, '2', '3', '10', '42', CURRENT_TIMESTAMP),
(NULL, '2', '3', '11', '64', CURRENT_TIMESTAMP),
(NULL, '2', '3', '12', '90', CURRENT_TIMESTAMP),
(NULL, '2', '3', '14', '120', CURRENT_TIMESTAMP);


INSERT INTO `products` (`id`, `design_id`, `name`, `created_at`) VALUES (NULL, '1', 'Emma Wiggles Cake', CURRENT_TIMESTAMP);

